# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GagsDev
email: ptrgags@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Hi, I'm Peter Gagliardi, and this is my blog dedicated to my
    GitHub projects and other computer science/physics/math topics!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ptrgags.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  ptrgags

# Build settings
markdown: kramdown
