// Generated by CoffeeScript 1.10.0
(function() {
  this.repos = {};

  this.fetch_repos = function() {
    return $.getJSON(urls.dropbox_repos, "", function(repos) {
      var repo, repo_name;
      for (repo_name in repos) {
        repo = repos[repo_name];
        process_repo(repo_name, repo);
      }
      return refresh();
    });
  };

  this.process_repo = function(repo_name, repo_obj) {
    return repos[repo_name] = repo_obj;
  };

  fetch_repos();

}).call(this);
