// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  this.Widget = (function() {
    function Widget() {}

    Widget.prototype.render = function() {
      return $("<p>").html("Widget");
    };

    return Widget;

  })();

  this.HomeCard = (function(superClass) {
    extend(HomeCard, superClass);

    function HomeCard() {
      return HomeCard.__super__.constructor.apply(this, arguments);
    }

    HomeCard.prototype.render = function() {
      var panel, panel_body;
      panel = $('<div>').addClass('panel panel-default');
      panel_body = $("<div>").addClass('panel-body').appendTo(panel);
      $("<h2>").html("Welcome").appendTo(panel_body);
      $("<p>").html("Hello, my name is Peter Gagliardi. Welcome to my GitHub website! This site is my portfolio of programming projects. It fetches data about my public GitHub repositories and presents them all in one place.").appendTo(panel_body);
      $("<p>").html("I have a backend script + cron job that fetches my GitHub data and makes it accessible to the site. As a result, this site updates its content automatically at least once a week, even if I forget to run the script.").appendTo(panel_body);
      $("<p>").html("This website is a work in progress. There are many more features I would like to add over time, but I'm usually working on other projects.").appendTo(panel_body);
      return panel;
    };

    return HomeCard;

  })(Widget);

  this.IdeasCard = (function(superClass) {
    extend(IdeasCard, superClass);

    function IdeasCard(ideas) {
      this.ideas = ideas;
    }

    IdeasCard.prototype.render = function() {
      var i, idea, len, panel, panel_body, ref, ul;
      panel = $('<div>').addClass('panel panel-default');
      panel_body = $("<div>").addClass('panel-body').appendTo(panel);
      $('<p>').html("This is a list of possible future projects I'd be interested in trying. I probably won't find time for most of them, but if enough people ask me about a single idea, I might consider making it a project.").appendTo(panel_body);
      $('<p>').html("Feel free to take inspiration from this list! If you develop something cool, let me know at ptrgags@gmail.com. I'd love to hear about it!").appendTo(panel_body);
      ul = $("<ul>").appendTo(panel_body);
      ref = this.ideas;
      for (i = 0, len = ref.length; i < len; i++) {
        idea = ref[i];
        $("<li>").html(idea).appendTo(ul);
      }
      return panel;
    };

    return IdeasCard;

  })(Widget);

  this.ProjectCard = (function(superClass) {
    extend(ProjectCard, superClass);

    function ProjectCard(project) {
      this.project = project;
    }

    ProjectCard.prototype.render = function() {
      var buttons, description, klass, panel, panel_body, tags, text;
      panel = $("<div>").addClass('panel panel-default');
      panel_body = $("<div>").addClass('panel-body').appendTo(panel);
      $("<h2>").html(this.project.title).appendTo(panel_body);
      tags = $("<p>").appendTo(panel_body);
      description = $("<p>").html(this.project.description).appendTo(panel_body);
      if (this.project.version_tag != null) {
        if (this.project.version_tag === "") {
          text = "No Releases";
          klass = "label label-danger";
        } else {
          text = this.project.version_tag;
          klass = 'label label-success';
        }
        $("<span>").addClass(klass).html(text).appendTo(tags);
      }
      $("<span>").addClass("label label-primary").html(this.project.years).appendTo(tags);
      buttons = $('<div>').addClass("btn-group").appendTo(panel_body);
      if (this.project.github_link != null) {
        $('<a role="button">').prop("href", this.project.github_link).addClass("btn btn-success").html("View on GitHub").appendTo(buttons);
      }
      if ((this.project.github_page != null) && this.project.github_page !== "") {
        $('<a role="button">').prop("href", this.project.github_page).addClass("btn btn-success").html("View GitHub Page").appendTo(buttons);
      }
      return panel;
    };

    return ProjectCard;

  })(Widget);

}).call(this);
