// Generated by CoffeeScript 1.10.0
(function() {
  this.ideas = ["Count how many times a day one types ls in Bash", "Computer storage space idle game", "Arc Robot Simulator (based on Project Euler 208)", "Random Sentence Generator using grammars", "Elevator/Train AI simulation", "Crazy unit conversions", "Poker probabilities", "Machi Koro clone", "Network of microcontollers/single-board computers", "Interactive games instead of PowerPoints"];

}).call(this);
