// Generated by CoffeeScript 1.10.0
(function() {
  var NUM_COLS;

  NUM_COLS = 2;

  this.refresh = function() {
    switch (location.hash) {
      case "":
        return show_repos();
      case "#projects":
        return show_repos();
      case "#ideas":
        return show_ideas();
      default:
        return console.warn("Invalid hash... Fix this");
    }
  };

  this.score = function(proj) {
    var val;
    val = 0;
    if (proj.priority != null) {
      val |= 0x04;
    }
    if (proj.version != null) {
      val |= 0x02;
    }
    if ((proj.dev_status != null) && proj.dev_status === 'development') {
      val |= 0x01;
    }
    return val;
  };

  this.sort_projects = function(a, b) {
    var a_score, b_score;
    a_score = score(a);
    b_score = score(b);
    if (a_score > b_score) {
      return -1;
    }
    if (a_score < b_score) {
      return 1;
    }
    if (a.title.toLowerCase() < b.title.toLowerCase()) {
      return -1;
    }
    if (a.title.toLowerCase() > b.title.toLowerCase()) {
      return 1;
    }
    return 0;
  };

  this.show_ideas = function() {
    var ideas_widget;
    $("#content").html("");
    $("<h1>").html("Future Project Ideas").appendTo("#content");
    ideas_widget = new IdeasCard(ideas);
    return $("#content").append(ideas_widget.render());
  };

  this.show_repos = function() {
    var card, col, column, i, len, repo, results, row;
    $("#content").html("");
    $("<h1>").html("My GitHub Projects").appendTo("#content");
    column = 0;
    row = null;
    results = [];
    for (i = 0, len = repos.length; i < len; i++) {
      repo = repos[i];
      if (column === 0) {
        row = $('<div>').addClass("row").appendTo('#content');
      }
      col = $('<div>').addClass("col-sm-" + (Math.floor(12 / NUM_COLS))).appendTo(row);
      card = new ProjectCard(repo);
      $(col).append(card.render());
      results.push(column = (column + 1) % NUM_COLS);
    }
    return results;
  };

  this.ideas = [];

  this.fetch_ideas = function() {
    return $.getJSON(urls.dropbox_ideas, "", function(data) {
      window.ideas = data;
      return refresh();
    });
  };

  fetch_ideas();


  /*
  @fetch_data = ->
      base_url = "https://dl.dropboxusercontent.com/u/25993970/github/website"
      projects_url = "#{base_url}/projects.json"
      ideas_url = "#{base_url}/ideas.json"
      $.getJSON projects_url, "", (data) ->
          window.projects = data
          if location.hash is "#projects" or location.hash is ""
              show_projects()
      $.getJSON ideas_url, "", (data) ->
          window.ideas = data
          if location.hash is "#ideas"
              show_ideas()
  fetch_data()
   */

  this.onload = function() {
    $("#btn-github").click(refresh);
    $("#btn-ideas").click(refresh);
    return refresh();
  };

}).call(this);
