// Generated by CoffeeScript 1.10.0
(function() {
  this.projects = {
    linux_login: {
      title: "Linux Login",
      description: "Handy Bash customization scripts",
      version: "1.1",
      dev_number: "1.2",
      github_link: "linux-login"
    },
    turn_based_strategy: {
      title: "Turn-Based Strategy",
      description: "Library for making turn-based strategy games",
      version: "0.1",
      "with": "IzzyEevee",
      dev_number: "1.0",
      dev_status: "development",
      github_link: "tactical-strategy-lib",
      dropbox_link: "turn-based-strategy/index.html",
      drobox_version_prefix: "Demo"
    },
    byte_cards: {
      title: "ByteCards",
      "with": "KarishmaChanglani",
      description: "Next generation of digital playing cards",
      dev_number: "1.0",
      dev_status: "development",
      github_link: "byte-cards"
    },
    arduino_morse: {
      title: "Arduino Morse",
      version: "0.1",
      dev_number: "1.0",
      description: "Text to morse code library with Arduino-powered beacon",
      github_link: "arduino-morse"
    },
    square_runner: {
      title: "Square Runner",
      dev_number: "1.0",
      github_link: "square-runner",
      description: "Porting an old game to HTML5"
    },
    text_visualizer: {
      title: "Text Visualizer",
      description: "Visualization of hashed text",
      github_link: "text-visualizer",
      dropbox_link: "text-visualizer/v0.1/index.html",
      dropbox_version_prefix: "Demo",
      version: "0.1",
      dev_number: "1.0"
    },
    ptrgags_github_io: {
      title: "Website",
      description: "This website. Still under development",
      version: "0.2.1",
      dev_number: "1.0",
      github_link: "ptrgags.github.io",
      link: "http://ptrgags.github.io",
      link_text: "View Version 0.2.1"
    },
    mixtape: {
      title: "Mixtape",
      description: "Music programmed with Sonic Pi",
      dev_number: "1.0",
      github_link: "mixtape"
    },
    spinograph: {
      title: "Spin-o-Sketch",
      description: "Spinograph/Etch-A-Sketch",
      version: "1.0",
      dev_number: "2.0",
      github_link: "spin-o-sketch",
      dropbox_link: "spin-o-sketch/index.html",
      dropbox_version_prefix: "Version"
    }
  };

}).call(this);
