// Generated by CoffeeScript 1.10.0
(function() {
  this.urls = {};

  urls.dropbox_base = "https://dl.dropboxusercontent.com/u/25993970/github/website";

  urls.dropbox_repos = urls.dropbox_base + "/gagsdev.json";

  urls.dropbox_ideas = urls.dropbox_base + "/ideas.json";

}).call(this);
