// Generated by CoffeeScript 1.10.0
(function() {
  this.urls = {};

  urls.dropbox_base = "https://dl.dropboxusercontent.com/u/25993970/github/website";

  urls.dropbox_ideas = urls.dropbox_base + "/ideas.json";

  urls.github_user_url = "https://api.github.com/users/ptrgags";

  urls.github_repos_url = urls.github_user_url + "/repos";

}).call(this);
