name: 'Run Unit Tests'
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use latest Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Install npm packages
        run: npm install
      - name: run tests
        run: npm test
